project_id = "gyrbaqchbjxxjblpfkxc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54328

[edge_functions]
enabled = true
port = 54329

[analytics]
enabled = false

[functions.analyze-screenshot]
verify_jwt = true

[functions.analyze-url]
verify_jwt = true