// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyrbaqchbjxxjblpfkxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5cmJhcWNoYmp4eGpibHBma3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjE4NTgsImV4cCI6MjA2OTU5Nzg1OH0.AnWv-qHm48RJpMWeEFnq81Hpg4sA6dgfY7AbfOUo9J8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});